// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkkxKSUXhr5StLXtDFJCFjJhonU5otwHE',
    appId: '1:801104497512:web:47c2296b20c9e54b46e4dd',
    messagingSenderId: '801104497512',
    projectId: 'lumia-a17be',
    authDomain: 'lumia-a17be.firebaseapp.com',
    storageBucket: 'lumia-a17be.appspot.com',
    measurementId: 'G-1QE27PFHL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrXQXieg2Ue9jSxGvlbKspye_WWc5nkRU',
    appId: '1:801104497512:android:47ffb896e33fd0fb46e4dd',
    messagingSenderId: '801104497512',
    projectId: 'lumia-a17be',
    storageBucket: 'lumia-a17be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCc2fPALQXfVrewE-aF69-eHUEnUyXIH0',
    appId: '1:801104497512:ios:b108ec01da0269e246e4dd',
    messagingSenderId: '801104497512',
    projectId: 'lumia-a17be',
    storageBucket: 'lumia-a17be.appspot.com',
    iosBundleId: 'com.example.lumia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCc2fPALQXfVrewE-aF69-eHUEnUyXIH0',
    appId: '1:801104497512:ios:b9863f2bc17ed25946e4dd',
    messagingSenderId: '801104497512',
    projectId: 'lumia-a17be',
    storageBucket: 'lumia-a17be.appspot.com',
    iosBundleId: 'com.example.lumia.RunnerTests',
  );
}
